sudo: required
language: bash
services:
  - docker

env:
  global:
    - secure: JFdiQ4JR6Xyc1aFsKse23ev9iPzEbNuJU+W6u7aeXTE2JJOkTpneGBiP1+8mTOxO3QNH28fmKBBHRARIEXW7vi0biKhOiOei/vWFxobvKw+O4P9KylBhK0xrQeHl8fUEOFHnbQcQajVS+rKrAs9CNMqVX4Cg816uV+sdqJQSmcfEcC4BhamiiCg6AL42BFFcX+uDljO2uVw977zi1ToCc3RPVx9/XVuEfPunj03mbbu2vE41pdhE1+bg5bWxTusYKe08ZN8cLxxBjwE685yyPrEKEUDTNrRdbtKc7HXdQBtBfcyXlq/Ftaf/dKP9Kq6aXd/ZwOX2cwn1Dk6DHAyIdZV734Z6QFTzKKnnZOLw2rNLmLRtuM2ZoWH9pZoYEvKK9zxZdDn0dLbbhjREqpeLl3sLPTzV82HFPi5RkdYayV72q8SsRcRIf/i7ptOob5RHEThEpwzEdiHBOLpWJ3+xknB09q7nYDj6/fRQblPxSCdzMekh5+FgcSTzJytNfCvLh2oHqoz2q1jiQUG1ZJNmfQo/IoqNVK04IBuz3BHD6KyGY6y89h5GGcp2lfcekUDbO8hUTh7a2K9fuekP3MQ7bP19yr82HoENa0qVL1uA/LLRPSgVYxayBJwI6eWJDrvimngRnnZ4cPL4f6bXygleXsL54iSmuEEy5/WGQZc2ahI=
    - COMMIT_AUTHOR_MAIL: "doc-team@suse.com"
    # If you want to see a list of installed packages in the doc-ci docker container, set to TRUE
    - LIST_PACKAGES=0
    # List branches that should be published on GitHub pages, omit the maintenance/ prefix
    - PUBLISH_PRODUCTS="SLEHA12"

before_install:
  - echo "TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST" >> env.list
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH" >> env.list
  - echo "SOURCE_BRANCH=$SOURCE_BRANCH" >> env.list
  - echo "TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG" >> env.list
  - echo "LIST_PACKAGES=$LIST_PACKAGES" >> env.list
  - echo "PUBLISH_PRODUCTS=\"$PUBLISH_PRODUCTS\"" >> env.list
  - echo "ENCRYPTED_PRIVKEY_SECRET=$ENCRYPTED_PRIVKEY_SECRET" >> env.list
  - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT" >> env.list
  - wget https://raw.githubusercontent.com/openSUSE/doc-ci/develop/travis/travis.sh
  - ls
  - echo "Building docker image"
  - docker build -t sle-doc-image .

script:
  - docker run --rm -it sle-doc-image /bin/bash -c '/bin/bash travis.sh'

notifications:
  email:
    on_success: change
    on_failure: always
